AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10


Metrics/LineLength:
  Max: 150
  Exclude:
    - 'spec/pesapal_merchant_spec.rb'

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false
